// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Option struct {
	Value string `json:"value"`
}

type Player struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Room *Room  `json:"room"`
}

type Room struct {
	ID      string    `json:"id"`
	Players []*Player `json:"players"`
	Votes   []*Vote   `json:"votes"`
	Voting  bool      `json:"voting"`
	Options []*Option `json:"options"`
}

type Vote struct {
	Player    *Player `json:"player"`
	Room      *Room   `json:"room"`
	Option    *Option `json:"option"`
	TimeStamp string  `json:"timeStamp"`
}
